services:

  certmaker:
    image: alpine:3.18
    command:
      - /bin/sh
      - /deploy/make_certs.sh
    volumes:
      - ./deploy/make_certs.sh:/deploy/make_certs.sh
      - certs:/certs

  htsget:
    image: harbor.nbis.se/gdi/htsget-rs:latest
    command: ["htsget-actix", "--config", "/config/download-config.toml"]
    depends_on:
      certmaker:
        condition: service_completed_successfully
    ports:
      - 8088:8080
    #environment:
    #  - FORMATTING_STYLE=Pretty
    #  - RUST_LOG=debug
    volumes:
      - ./config-htsget-rs:/config/
      - certs:/certs
    extra_hosts:
      - dockerhost:host-gateway

volumes:
  certs:
