services:
  s3-archive:
    image: minio/minio:RELEASE.2023-02-10T18-48-39Z
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=access
      - MINIO_ROOT_PASSWORD=secretkey
      - MINIO_SERVER_URL=http://127.0.0.1:9000
    healthcheck:
      test: ["CMD", "curl", "-fkq", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - data:/data

  add-s3-data:
    image: minio/mc:RELEASE.2023-01-28T20-29-38Z
    depends_on:
      s3-archive:
        condition: service_healthy
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add s3 http://s3-archive:9000 access secretkey;
      /usr/bin/mc mb -p s3/archive;
      /usr/bin/mc policy set public s3/archive;
      /usr/bin/mc cp /data/* s3/archive/;
      /usr/bin/mc anonymous set public s3/archive/;
      "
    volumes:
      - ./data:/data

  server:
    image: ga4gh/htsget-refserver:1.5.1
    command:
      - /usr/src/app/htsget-refserver
      - -config
      - /config/config.json
    ports:
      - 3000:3000
    volumes:
      - ./config:/config
      - ./logs:/logs
  
  client:
    image: python:3.11-slim
    command:
      - /bin/bash
      - -c
      - apt update; apt install -y curl;
        if ! which htsget >/dev/null; then pip install htsget; fi;
        while true; do sleep 250; done
  
  samtools:
    image: staphb/samtools
    command:
      - /bin/bash
      - -c 
      - apt update; apt install -y curl;
        while true; do sleep 250; done
volumes:
  data: