ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
ticket_server_cert = "/certs/fullchain.pem"
ticket_server_key = "/certs/privkey.pem"

[[resolvers]]
regex = "(.*)"
substitution_string = "$1"

# The keys are defining whether the data is encrypted or not
#object_type.private_key = "/config/c4gh.sec.pem"
#object_type.public_key = "/config/c4gh.pub.pem"

# Send the headers back and forth
storage.forward_headers = true
response_scheme = "http"

# The index file
storage.endpoints.index = "http://dockerhost:8443/s3/"
# Header and file url
storage.endpoints.file = "http://dockerhost:8443/s3/"

# The url that will be used for the client's url
storage.response_url = "http://localhost:8443/s3/"

# Not yet implemented, will allow to send encrypted or unencrypted data to the client
# object_type.send_unencrypted_to_client = false