data_server_addr = "0.0.0.0:8081"
ticket_server_addr = "0.0.0.0:8080"
ticket_server_cors_allow_origins = "All"
ticket_server_cert = "/certs/fullchain.pem"
ticket_server_key = "/certs/privkey.pem"

[[resolvers]]
regex = "(.*)"
substitution_string = "$1"

[resolvers.object_type]
private_key = "/config/c4gh.sec.pem"
public_key = "/config/c4gh.pub.pem"

[resolvers.storage.endpoints]
forward_headers = true
response_scheme = "http"
index = "http://dockerhost:8443/s3/"
# Header and file url
file = "http://dockerhost:8443/s3-encrypted/"

# url = "http://dockerhost:8443/s3-encrypted/"
# The url that will be used for the client's url
response_url = "http://localhost:8443/s3/"
